---
title: "Analysis"
output: pdf_document
date: "2025-10-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages}

library(tidyverse)
library(ggplot2)
library(igraph)
library(kableExtra)
library(webshot2)
library(ggraph)

options("encoding" = "UTF-8")
```

```{r load data}

main_data <- read_csv("data_ready.csv")
distance_data<- read.csv("output_df.csv", header = TRUE, fileEncoding = "UTF-8")
#check <- distance_data %>% dplyr::select(S2CF1.S2CF1, Gloss, IPAactual)
```

## Data

```{r summary data - full}

n_infants <- main_data %>% group_by(Subject, Language) %>% tally()
n_langs <- main_data %>% group_by(Language) %>% tally()
age_data <- main_data %>% summarise(mean_age = mean(Age),
                                     min_age = min(Age),
                                     max_age = max(Age),
                                     sd_age = sd(Age))

tokens_data <- n_infants %>% ungroup() %>% summarise(mean_tok = mean(n),
                                       min_tok = min(n),
                                       max_tok = max(n),
                                       sd_tok = sd(n))

types_data <- main_data %>% group_by(Subject, Gloss) %>% tally() %>%
  ungroup() %>%
  group_by(Subject) %>% tally() %>% summarise(mean_typ = mean(n),
                                       min_typ = min(n),
                                       max_typ = max(n),
                                       sd_typ = sd(n))

types_tokens <- main_data %>% group_by(Gloss) %>% tally() %>%
  summarise(n_typ = length(Gloss),
            n_tok = sum(n)) 


```

```{r summary data - disyllables}

disyl_data <- main_data %>% filter(nsyl_target == 2)

types_tokens <- disyl_data %>% group_by(Gloss) %>% tally() %>%
  summarise(n_typ = length(Gloss),
            n_tok = sum(n)) 

mean_tok_disyl <- disyl_data %>% 
  group_by(Subject) %>% 
  tally()%>% 
  ungroup() %>% 
  summarise(mean_tok = mean(n),
            sd_tok = sd(n))

mean_typ_disyl <- disyl_data %>% 
  group_by(Subject, Gloss) %>% 
  tally() %>%
  ungroup() %>%
  group_by(Subject) %>% 
  tally() %>% 
  summarise(mean_typ = mean(n),
            sd_typ = sd(n))

```

```{r table 1}

infants <- main_data %>% group_by(Language, Subject) %>% slice(1) %>% ungroup() %>%
  group_by(Language) %>% tally()

ages <- main_data %>% 
  group_by(Language) %>% 
  summarise(mean_age = mean(Age),
            sd_age = sd(Age)) %>%
  dplyr::select(-Language)

n_typ <- main_data %>% group_by(Subject, Language, Gloss) %>% tally() %>%
  ungroup() %>%
  group_by(Language, Subject) %>% 
  tally() %>% 
  summarise(mean_typ = mean(n),
            sd_typ = sd(n)) %>%
  dplyr::select(-Language)

n_tok <- main_data %>% 
  group_by(Language,Subject) %>% 
  tally() %>% 
  summarise(mean_tok = mean(n), 
            sd_tok = sd(n)) %>%
  dplyr::select(-Language)

n_typ_disyl <- disyl_data %>% group_by(Subject, Language, Gloss) %>% tally() %>%
  ungroup() %>%
  group_by(Language, Subject) %>% 
  tally() %>% 
  summarise(mean_typ_di = mean(n),
            sd_typ_di = sd(n)) %>%
  dplyr::select(-Language)

n_tok_disyl <- disyl_data %>% 
  group_by(Language,Subject) %>% 
  tally() %>% 
  summarise(mean_tok_di = mean(n), 
            sd_tok_di = sd(n)) %>%
  dplyr::select(-Language)

Table1 <- cbind(infants, ages, n_typ, n_tok, n_typ_disyl, n_tok_disyl) %>%
  mutate_if(is.numeric, ~round(., 2)) %>%
  mutate(sd_age = paste0("(", sd_age, ")"),
         sd_typ = paste0("(", sd_typ, ")"),
         sd_tok = paste0("(", sd_tok, ")"),
         sd_typ_di = paste0("(", sd_typ_di, ")"),
         sd_tok_di = paste0("(", sd_tok_di, ")")) %>%
  unite("Mean age (SD)", mean_age, sd_age, sep = " ") %>%
  unite("Mean word types (SD)", mean_typ, sd_typ, sep = " ") %>%
  unite("Mean word tokens (SD)", mean_tok, sd_tok, sep = " ") %>%
  unite("Mean word types (SD) (disyl. targets)", mean_typ_di, sd_typ_di, sep = " ") %>%
  unite("Mean word tokens (SD) (disyl. targets)", mean_tok_di, sd_tok_di, sep = " ") %>%
  rename("n infants" = n)

kable(Table1) %>% kable_styling("striped") %>% save_kable("Table1.pdf")
```

```{r Table 2 - Syllable numbers}

distance_data %>% filter(data_type == "actual" & nsyl_actual == 2)

distance_data %>% filter(data_type == "actual" & nsyl_actual == 2) %>% 
  tally() %>% 
  summarise(n_disyl = sum(n),
            pc_disyl = n_disyl/1794)

prop_syls <- distance_data %>% filter(data_type == "actual") %>% 
  group_by(nsyl_actual) %>% 
  tally() %>%  
  mutate(prop = n/1794) %>%
  mutate_if(is.numeric, ~round(., 2)) %>%
  rename("proportion" = prop) %>%
  dplyr::select(-n)

Table2 <- distance_data %>% filter(data_type == "actual") %>% 
  group_by(Language, nsyl_actual) %>% tally() %>% 
  pivot_wider(names_from = Language, values_from = n) %>%
  mutate_all(~replace(., is.na(.), 0)) %>%
  left_join(prop_syls) %>%
  rename("n syllables" = nsyl_actual)

  
kable(Table2) %>% kable_styling("striped") %>% save_kable("Table2.pdf")


prop_syls <- main_data %>%
  group_by(Subject, Language, Gloss) %>% slice(1) %>%
  ungroup() %>%
  group_by(Language) %>%
  tally() %>%
  rename("total" = "n")

Table2_allsyls <- main_data %>%
  group_by(Language, Subject, Gloss) %>%
  slice(1) %>%
  ungroup() %>%
  mutate(syllables = ifelse(nsyl_target >2, 3, nsyl_target)) %>%
  group_by(Language, syllables) %>%
  tally() %>%
  left_join(prop_syls) %>%
  mutate(proportion = n/total) %>%
  dplyr::select(-total, -n) %>%
  pivot_wider(names_from = Language, values_from = proportion) %>%
  mutate_all(~replace(., is.na(.), 0)) %>%
  rename("n syllables" = syllables) %>%
  mutate_if(is.numeric, ~round(., 2))

```

```{r ex of distance table}

Table3 <- distance_data %>% dplyr::select(Subject, Language, Gloss, IPAactual, 
                                S1C1.S1C1, #S1C2.S1C2, S1C3.S1C3, S1C4.S1C4,
                                S2C1.S2C1, #S2C2.S2C2, S2C3.S2C3, S2C4.S2C4,
                                SFC1.SFC1, #SFC2.SFC2, 
                                SFCF1.SFCF1, #SFCF2.SFCF2,
                                nsyl_actual, data_type
                                ) %>%
  filter(#S1C1.S1C1 != "0" &
           #nsyl_actual ==2 &
             data_type == "actual" & 
             Language == "UK") %>%
  group_by(Gloss) %>%
  slice(1) %>%
  filter(Gloss %in% c("cuddle", "cookie", "phuppo", "eeyore", "flowers")) %>%
  dplyr::select(-nsyl_actual, -data_type) %>%
  rename("IPA" = IPAactual)

names(Table3) <- c("Infant", "Language", "Gloss", "IPA", "Syl1-C1", "Syl2-C1", "FinalSyl-C1", "FinalC")

kable(Table3) %>% kable_styling("striped") %>% save_kable("Table3.pdf")

```

```{r ex of distance table - geminates}
#set.seed(24)

# Table4a <- distance_data %>%
#   filter(
#     geminate_T == T,
#     data_type == "target") %>%
#   group_by(Language, Gloss)  %>%
#   slice(1) %>%
#   mutate(`Data type` = ifelse(Subject == "Atte", "Target", "")
#          ) %>%
#   dplyr::select(`Data type`,Subject, Language, Gloss, IPAtarget,
#                                 S1C1.S1C1, #S1C2.S1C2, S1C3.S1C3, S1C4.S1C4,
#                                 S1CF1.S1CF1, S1CF2.S1CF2,
#                                 S2C1.S2C1, S2CF1.S2CF1, #S2C2.S2C2, S2C3.S2C3, S2C4.S2C4,
#                                 SFC1.SFC1, #SFC2.SFC2,
#                                 #SFCF1.SFCF1, SFCF2.SFCF2,
#                                 ) %>%
#   filter(Gloss %in% c("ankka", "hot", "cookie", "phuppo")) %>%
#   rename("IPA" = IPAtarget) %>%
#   mutate(Gloss = fct_recode(Gloss,
#                             "ankka 'duck'" = "ankka",
#                             "kukki 'cookie'" = "cookie",
#                             "atsui 'hot" = "hot",
#                             "phuppo 'uncle'" = "phuppo"),
#          )
# 
# names(Table4a) <- sub(".*.", "", names(Table4a))
# names(Table4a)
# 
# Table4b <- distance_data %>%
#   filter(
#     geminate_A == T,
#     data_type == "actual") %>%
#   group_by(Language, Gloss)  %>%
#   slice(1) %>%
#   mutate(`Data type` = ifelse(Subject == "Mira", "Actual", "")
#          ) %>%
#   dplyr::select(`Data type`, Subject, Language, Gloss, IPAactual,
#                                 S1C1.S1C1, #S1C2.S1C2, S1C3.S1C3, S1C4.S1C4,
#                                 S1CF1.S1CF1, S1CF2.S1CF2,
#                                 S2C1.S2C1, S2CF1.S2CF1,#S2C2.S2C2, S2C3.S2C3, S2C4.S2C4,
#                                 SFC1.SFC1, #SFC2.SFC2,
#                                 #SFCF1.SFCF1, SFCF2.SFCF2
#                                 ) %>%
#    filter(Gloss %in% c("häntä", "roska", "cassé", "Mummy")) %>%
#    rename("IPA" = IPAactual) %>%
#   mutate(Gloss = fct_recode(Gloss,
#                             "häntä 'him'" = "häntä",
#                             "roska 'rubbish'" = "roska",
#                             "cassé 'broken" = "cassé"))
# 
# names(Table4b) <- sub(".*.", "", names(Table4b))
# names(Table4b)
# 
# Table4 <- rbind(Table4a, Table4b)
# 
# kable(Table4) %>% kable_styling("striped") %>% save_kable("Table4.pdf")

```



```{r distance matrix}

#source("mini_matrix.R")

```


```{r iterative networks analysis}

smallworlddata_it <- read_csv("globalsmallworlddata_iter.csv")

```


```{r Table 5}

Table5_base <- smallworlddata_it %>%
  dplyr::select(-Speaker, -Speaker_ID, -ID) %>%
  group_by(Language, data_type) %>%
  summarise(mean_CC = mean(clust_coef_global),
            #sd_CC = sd(clust_coef_global),
            mean_k = mean(mean_k),
           # sd_k = sd(mean_k),
            mean_PL = mean(path_length)
            #sd_PL = sd(path_length)
            ) %>% 
  pivot_wider(names_from = data_type,
    values_from = c(mean_CC, mean_k, mean_PL)
  )%>%
   mutate_if(is.numeric, ~round(., 2)) #%>%
  # mutate(mean_CC_iter_A = as.character(mean_CC_iter_A),
  #        mean_CC_iter_T = as.character(mean_CC_iter_T),
  #        mean_k_iter_T = as.character(mean_k_iter_T),
  #        mean_k_iter_A = as.character(mean_k_iter_A),
  #        mean_PL_iter_A = as.character(mean_PL_iter_A),
  #        mean_PL_iter_T = as.character(mean_PL_iter_T))

Table5_means <-  Table5_base %>% 
  ungroup() %>%
  summarise_if(is.numeric, mean, na.rm = TRUE) %>%
 # mutate(Language = "Mean") %>% 
  pivot_longer(
  cols = 1:6,
  names_to = "var",
  values_to = "mean"
  )

Table5_sd <-  Table5_base %>%
  ungroup() %>%
  summarise_if(is.numeric, sd, na.rm = TRUE) %>%
    pivot_longer(
  cols = 1:6,
  names_to = "var",
  values_to = "sd"
  )

Table5_mean_sd <- cbind(Table5_means, Table5_sd) %>%
  dplyr::select(-3) %>%
  mutate_if(is.numeric, ~round(., 2)) %>%
  mutate(sd = paste0("(", sd, ")")) %>%
  unite("Mean (SD)", mean, sd, sep = " ") %>%
  pivot_wider(names_from = var,
    values_from = "Mean (SD)") %>%
  mutate(Language = "Mean (SD)")

Table5 <- Table5_base %>%
  mutate(mean_CC_iter_A = as.character(mean_CC_iter_A),
         mean_CC_iter_T = as.character(mean_CC_iter_T),
         mean_k_iter_T = as.character(mean_k_iter_T),
         mean_k_iter_A = as.character(mean_k_iter_A),
         mean_PL_iter_A = as.character(mean_PL_iter_A),
         mean_PL_iter_T = as.character(mean_PL_iter_T)) %>%
  rbind(Table5_mean_sd) %>%
  rename(
    "Clustering coeff. (A)" = mean_CC_iter_A,
    "Clustering coeff. (T)" = mean_CC_iter_T,
    "Mean k (A)" = mean_k_iter_A,
    "Mean k (T)" = mean_k_iter_T,
    "Path length (A)" = mean_PL_iter_A,
    "Path length (T)" = mean_PL_iter_T
  )

kable(Table5) %>% kable_styling("striped") %>% save_kable("Table5.pdf")
```

```{r Figure 1}

# disyl_data %>% group_by(Subject) %>% tally() %>% summarise(min = min(n),
#                                                            max = max(n))

it_summary_networks <- smallworlddata_it %>% 
  filter(data_type == "iter_A") %>%
  group_by(Speaker, Language) %>%
  summarise(path_length = mean(path_length),
            mean_k = mean(mean_k),
            clust_coef = mean(clust_coef_global))

network_graphs_long <- smallworlddata_it %>% pivot_longer(
  cols = path_length:clust_coef_global,
  names_to = "var",
  values_to = "value"
) #%>%
  # group_by(Speaker, var, Language, data_type) %>%
  # summarize(value = mean(value))

Fig1 <- network_graphs_long %>%
  mutate(var = fct_recode(var,
                          "Clustering coefficient" = "clust_coef_global",
                          "Mean k" = "mean_k",
                          "Path length" = "path_length"),
        data_type = fct_recode(data_type,
        "Actual" = "iter_A",
        "Target" = "iter_T")) %>%
  ggplot(aes(x = Language, y = value, colour = data_type)) +
  geom_boxplot(aes(fill = data_type), alpha = .8) +
  geom_point(shape = 1, position = position_jitterdodge(), alpha=.1) +
  scale_colour_brewer(palette = "Set1") +
  theme_bw(base_size = 14) +
  theme(legend.title = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 0.7)) +
  facet_wrap(~var, ncol = 3, scales = "free")


```

Fig1
```{r top and bottom infants}

top_infants_meank <- it_summary_networks %>%
  arrange(desc(mean_k)) %>%
  head(5) %>%
  dplyr::select(mean_k, Speaker, Language) %>%
  mutate(Measure = "Mean k") %>%
  rename("Value" = mean_k)

top_infants_PL <- it_summary_networks %>%
  arrange(path_length) %>%
  head(5) %>%
  dplyr::select(path_length, Speaker, Language) %>%
  mutate(Measure = "Path length") %>%
  rename("Value" = path_length)

top_infants_CC <- it_summary_networks %>%
  arrange(desc(clust_coef)) %>%
  head(5) %>%
  dplyr::select(clust_coef, Speaker, Language) %>%
  mutate(Measure = "Clust. coef.") %>%
  rename("Value" = clust_coef)

top_infants <- rbind(top_infants_CC, top_infants_meank, top_infants_PL) %>%
  mutate_if(is.numeric, ~round(., 2)) %>%
  dplyr::select(Measure, Speaker, Language, Value) %>%
  mutate(order = "top")

bottom_infants_meank <- it_summary_networks %>%
  arrange(mean_k) %>%
  head(5) %>%
  dplyr::select(mean_k, Speaker, Language) %>%
  mutate(Measure = "Mean k",) %>%
  rename("Value" = mean_k)

bottom_infants_PL <- it_summary_networks %>%
  arrange(desc(path_length)) %>%
  head(5) %>%
  dplyr::select(path_length, Speaker, Language) %>%
  mutate(Measure = "Path length") %>%
  rename("Value" = path_length)

bottom_infants_CC <- it_summary_networks %>%
  arrange(clust_coef) %>%
  head(5) %>%
  dplyr::select(clust_coef, Speaker, Language) %>%
  mutate(Measure = "Clust. coef.") %>%
  rename("Value" = clust_coef)

bottom_infants <- rbind(bottom_infants_CC, bottom_infants_meank, bottom_infants_PL) %>%
  mutate_if(is.numeric, ~round(., 2)) %>%
  dplyr::select(Measure, Speaker, Language, Value) %>%
  mutate(order = "bottom")

kable(bottom_infants) %>% kable_styling("striped") %>% save_kable("Table6b.pdf")
kable(top_infants) %>% kable_styling("striped") %>% save_kable("Table6a.pdf")

all_infants <- rbind(top_infants, bottom_infants) %>% group_by(Speaker, order) %>% tally()
```

## Comparison with template analysis

```{r network graphs for high template infants - Atte}

atte_01_tab <- read.table("atte_01_A.txt",header=TRUE,row.names=1)   ### need to update these

atte_01 <- as.matrix(atte_01_tab)

words_atte_01 <- as.data.frame(dimnames(atte_01))

words_atte_01_alph <- gsub('[0-9.]', '', words_atte_01[1])

dimnames(atte_01) <- list(NULL, c("matto", "Atti", "auto", "auto", "ukko", "Minni", "auto", "auto", "auto", "auto", "Atti", "ukko", "isi", "äiti", "loppu", "matto", "äiti", "äiti", "Atti", "ääni"))
  

# standardize values

Q1_atte_01 <- quantile(atte_01[atte_01 > 0], 0.25)

atte_01 <- ifelse(atte_01>Q1_atte_01, NA, atte_01)
atte_01 <- ifelse(atte_01==0, 0.1, atte_01)


# Transform it in a network graph format
network_atte_01 <- graph_from_adjacency_matrix(atte_01, weighted = TRUE, diag=F)

# Remove edges with NA weights
network_atte_01 <- delete_edges(network_atte_01, 
                                  E(network_atte_01)[is.na(E(network_atte_01)$weight)])

flip <- function(x) max(x)-x+1  # function to flip the values so that wider edges = closer connection

# Make the graph
atte_01_graph <- ggraph(network_atte_01, layout = "stress") +
  geom_edge_link(aes(edge_width=(edge_width=flip(weight)),
                     edge_colour = weight),
                # edge_colour="grey", 
                 edge_alpha=0.2) +
  geom_node_point(fill="#69b3a2", 
                  colour = "grey36",
                  size=3, stroke = 1.2, shape = 21) +
  geom_node_text(aes(label=name),
                 repel = TRUE, size=4#, color="#69b3a2"
                 ) +
  theme_void(base_size = 14) +
  ggtitle("Atte (Finnish): 100% templates") +
  theme(
    legend.position="none",
    plot.margin=unit(rep(1,4), "cm")
  )
```
atte_01_graph

```{r network graphs for high template infants - eelis}

eelis_01_tab <- read.table("eelis_01_A.txt",header=TRUE,row.names=1)   ### need to update these

eelis_01 <- as.matrix(eelis_01_tab)

words_eelis_01 <- as.data.frame(dimnames(eelis_01))

words_eelis_01_alph <- gsub('[0-9.]', '', words_eelis_01[1])

dimnames(eelis_01) <- list(NULL, c("Hippi", "heppa", "heppa", "heppa", "istuu", "kiinni", "pappa", "heppa", "kiinni", "loppu", "heppa", "ankka", "heppa", "istuu", "heppa", "kiinni", "kakka", "Hippi", "heppa", "kukka"))
  

# standardize values

Q1_eelis_01 <- quantile(eelis_01[eelis_01 > 0], 0.25)

eelis_01 <- ifelse(eelis_01>Q1_eelis_01, NA, eelis_01)
eelis_01 <- ifelse(eelis_01==0, 0.1, eelis_01)


# Transform it in a network graph format
network_eelis_01 <- graph_from_adjacency_matrix(eelis_01, weighted = TRUE, diag=F)

# Remove edges with NA weights
network_eelis_01 <- delete_edges(network_eelis_01, 
                                  E(network_eelis_01)[is.na(E(network_eelis_01)$weight)])

flip <- function(x) max(x)-x+1  # function to flip the values so that wider edges = closer connection

# Make the graph
eelis_01_graph <- ggraph(network_eelis_01, layout = "stress") +
  geom_edge_link(aes(edge_width=(edge_width=flip(weight)),
                     edge_colour = weight),
                # edge_colour="grey", 
                 edge_alpha=0.2) +
  geom_node_point(fill="#69b3a2", 
                  colour = "grey36",
                  size=3, stroke = 1.2, shape = 21) +
  geom_node_text(aes(label=name),
                 repel = TRUE, size=4#, color="#69b3a2"
                 ) +
  theme_void(base_size = 14) +
  ggtitle("Eelis (Finnish): 88% templates") +
  theme(
    legend.position="none",
    plot.margin=unit(rep(1,4), "cm")
  )
```

eelis_01_graph

```{r network graphs for high template infants - basile}

basile_01_tab <- read.table("basile_01_A.txt",header=TRUE,row.names=1)   ### need to update these

basile_01 <- as.matrix(basile_01_tab)

words_basile_01 <- as.data.frame(dimnames(basile_01))

words_basile_01_alph <- gsub('[0-9.]', '', words_basile_01[1])

dimnames(basile_01) <- list(NULL, c("pin pon", "teuton", "canard/coin-coin", "encore", "livre", "divan", "canard/coin-coin", "canard/coin-coin", "lequel", "maman", "pin pon", "coucou", "pin pon", "musique", "bravo", "maman", "maman", "maman", "maman", "mouton"))
  

# standardize values

Q1_basile_01 <- quantile(basile_01[basile_01 > 0], 0.25)

basile_01 <- ifelse(basile_01>Q1_basile_01, NA, basile_01)
basile_01 <- ifelse(basile_01==0, 0.1, basile_01)


# Transform it in a network graph format
network_basile_01 <- graph_from_adjacency_matrix(basile_01, weighted = TRUE, diag=F)

# Remove edges with NA weights
network_basile_01 <- delete_edges(network_basile_01, 
                                  E(network_basile_01)[is.na(E(network_basile_01)$weight)])

flip <- function(x) max(x)-x+1  # function to flip the values so that wider edges = closer connection

# Make the graph
basile_01_graph <- ggraph(network_basile_01, layout = "stress") +
  geom_edge_link(aes(edge_width=(edge_width=flip(weight)),
                     edge_colour = weight),
                # edge_colour="grey", 
                 edge_alpha=0.2) +
  geom_node_point(fill="#69b3a2", 
                  colour = "grey36",
                  size=3, stroke = 1.2, shape = 21) +
  geom_node_text(aes(label=name),
                 repel = TRUE, size=4#, color="#69b3a2"
                 ) +
  theme_void(base_size = 14) +
  ggtitle("Basile (French): 93% templates") +
  theme(
    legend.position="none",
    plot.margin=unit(rep(1,4), "cm")
  )
```

basile_01_graph

```{r network graphs for low template infants - radia}

radia_01_tab <- read.table("radia_01_A.txt",header=TRUE,row.names=1)   ### need to update these

radia_01 <- as.matrix(radia_01_tab)

words_radia_01 <- as.data.frame(dimnames(radia_01))

words_radia_01_alph <- gsub('[0-9.]', '', words_radia_01[1])

dimnames(radia_01) <- list(NULL, c("toba", "machar", "machar", "MAMA", "MAMA", "ayee", "acha", "dadi", "oho", "BOTTLE", "theek hai", "khana", "ganda", "BASKET", "nino", "vava", "BOTTLE", "sona", "vava", "Allah"))

# standardize values

Q1_radia_01 <- quantile(radia_01[radia_01 > 0], 0.25)

radia_01 <- ifelse(radia_01>Q1_radia_01, NA, radia_01)
radia_01 <- ifelse(radia_01==0, 0.1, radia_01)


# Transform it in a network graph format
network_radia_01 <- graph_from_adjacency_matrix(radia_01, weighted = TRUE, diag=F)

# Remove edges with NA weights
network_radia_01 <- delete_edges(network_radia_01, 
                                  E(network_radia_01)[is.na(E(network_radia_01)$weight)])

flip <- function(x) max(x)-x+1  # function to flip the values so that wider edges = closer connection

# Make the graph
radia_01_graph <- ggraph(network_radia_01, layout = "stress") +
  geom_edge_link(aes(edge_width=(edge_width=flip(weight)),
                     edge_colour = weight),
                # edge_colour="grey", 
                 edge_alpha=0.2) +
  geom_node_point(fill="#69b3a2", 
                  colour = "grey36",
                  size=3, stroke = 1.2, shape = 21) +
  geom_node_text(aes(label=name),
                 repel = TRUE, size=4#, color="#69b3a2"
                 ) +
  theme_void(base_size = 14) +
  ggtitle("Radia (Urdu): 22% templates") +
  theme(
    legend.position="none",
    plot.margin=unit(rep(1,4), "cm")
  )
```

radia_01_graph

```{r network graphs for low template infants - julien}

julien_01_tab <- read.table("julien_01_A.txt",header=TRUE,row.names=1)   ### need to update these

julien_01 <- as.matrix(julien_01_tab)

words_julien_01 <- as.data.frame(dimnames(julien_01))

words_julien_01_alph <- gsub('[0-9.]', '', words_julien_01[1])

dimnames(julien_01) <- list(NULL, c("croco", "Tonton", "croco", "Pin pon", "Popi", "Papa", "Nana", "Corinne", "Maman", "plus grand", "Papa", "croco", "Papa", "croco", "Boubou", "les deux", "Boubou", "Pin pon", "Tonton", "Boubou"))
  

# standardize values

Q1_julien_01 <- quantile(julien_01[julien_01 > 0], 0.25)

julien_01 <- ifelse(julien_01>Q1_julien_01, NA, julien_01)
julien_01 <- ifelse(julien_01==0, 0.1, julien_01)


# Transform it in a network graph format
network_julien_01 <- graph_from_adjacency_matrix(julien_01, weighted = TRUE, diag=F)

# Remove edges with NA weights
network_julien_01 <- delete_edges(network_julien_01, 
                                  E(network_julien_01)[is.na(E(network_julien_01)$weight)])

flip <- function(x) max(x)-x+1  # function to flip the values so that wider edges = closer connection

# Make the graph
julien_01_graph <- ggraph(network_julien_01, layout = "stress") +
  geom_edge_link(aes(edge_width=(edge_width=flip(weight)),
                     edge_colour = weight),
                # edge_colour="grey", 
                 edge_alpha=0.2) +
  geom_node_point(fill="#69b3a2", 
                  colour = "grey36",
                  size=3, stroke = 1.2, shape = 21) +
  geom_node_text(aes(label=name),
                 repel = TRUE, size=4#, color="#69b3a2"
                 ) +
  theme_void(base_size = 14) +
  ggtitle("Julien (French): 0% templates") +
  theme(
    legend.position="none",
    plot.margin=unit(rep(1,4), "cm")
  )
```

julien_01_graph

```{r network graphs for low template infants - lewis}

lewis_01_tab <- read.table("lewis_01_A.txt",header=TRUE,row.names=1)   ### need to update these

lewis_01 <- as.matrix(lewis_01_tab)

words_lewis_01 <- as.data.frame(dimnames(lewis_01))

words_lewis_01_alph <- gsub('[0-9.]', '', words_lewis_01[1])

dimnames(lewis_01) <- list(NULL, c("uh-oh", "pushchair", "choo-choo", "oh no", "all gone", "tractor", "apple", "all gone", "uh-oh", "uh-oh", "all gone", "oh no", "choo-choo", "all gone", "choo-choo", "tractor", "all gone", "oh no", "oh no", "all gone"))
  

# standardize values

Q1_lewis_01 <- quantile(lewis_01[lewis_01 > 0], 0.25)

lewis_01 <- ifelse(lewis_01>Q1_lewis_01, NA, lewis_01)
lewis_01 <- ifelse(lewis_01==0, 0.1, lewis_01)


# Transform it in a network graph format
network_lewis_01 <- graph_from_adjacency_matrix(lewis_01, weighted = TRUE, diag=F)

# Remove edges with NA weights
network_lewis_01 <- delete_edges(network_lewis_01, 
                                  E(network_lewis_01)[is.na(E(network_lewis_01)$weight)])

flip <- function(x) max(x)-x+1  # function to flip the values so that wider edges = closer connection

# Make the graph
lewis_01_graph <- ggraph(network_lewis_01, layout = "stress") +
  geom_edge_link(aes(edge_width=(edge_width=flip(weight)),
                     edge_colour = weight),
                # edge_colour="grey", 
                 edge_alpha=0.2) +
  geom_node_point(fill="#69b3a2", 
                  colour = "grey36",
                  size=3, stroke = 1.2, shape = 21) +
  geom_node_text(aes(label=name),
                 repel = TRUE, size=4#, color="#69b3a2"
                 ) +
  theme_void(base_size = 14) +
  ggtitle("Lewis (English): 30% templates") +
  theme(
    legend.position="none",
    plot.margin=unit(rep(1,4), "cm")
  )
```

lewis_01_graph


```{r julien example}

words_julien_01 <- as.data.frame(words_julien_01)

colnames(words_julien_01)[1] <- "words"

julien_IPA<- distance_data %>% unite(GlossID, "Gloss", "ID", sep = "", remove = F) %>%
  filter(GlossID %in% words_julien_01$words) %>%
  dplyr::select(Subject, Language, Gloss, IPAactual, 
                                S1C1.S1C1,
                S2C1.S2C1,
                                SFC1.SFC1, 
                                data_type) %>%
  filter(Subject == "Julien" & data_type == "actual") %>%
  group_by(Gloss) %>%
  slice(1) %>%
  dplyr::select(Gloss, IPAactual)

julien_ex <- distance_data %>% unite(GlossID, "Gloss", "ID", sep = "", remove = F) %>%
  filter(GlossID %in% words_julien_01$words) %>%
  dplyr::select(Subject, Language, Gloss, IPAactual, 
                                S1C1.S1C1,
                S2C1.S2C1,
                                SFC1.SFC1, 
                                data_type) %>%
  filter(      Subject == "Julien" &
               data_type == "actual"
               ) %>%
  dplyr::select(-Subject, -Language, -data_type) %>%
  group_by(Gloss, S1C1.S1C1, S2C1.S2C1, SFC1.SFC1) %>% tally() %>%
  left_join(julien_IPA) %>%
  dplyr::select(Gloss, IPAactual, S1C1.S1C1, S2C1.S2C1, SFC1.SFC1, n)


kable(julien_ex) %>% kable_styling("striped") %>% save_kable("julien_ex.pdf")

```